- src/cl/op-node/op_node_launcher.star
This gets around the following error starting up `op-node`:
```
failed to fetch runtime config data" err="failed to fetch unsafe block signing address from system config: failed to fetch proof of storage slot 0x65a7ed542fb37fe237fdfbdd70b31598523fe5b32879e307bae27a0bd9581c08 at block 0x26af2a02dc48831d3d002bf3c064af37e769f05aa3a0dbfa70c4967ba7887ed8: eth_getProof is unimplemented for historical blocks
```
A local l1, the neccassary deployments and config for an l2 and the l2 nodes starts with the following:
1. Checkout this branch and run 
```
kurtosis run path/to/optimism-package --args-file path/to/optimism-package/network_params.yaml
```
> fix: Trust L1 RPC

- src/el/op-reth/op_reth_launcher.star
Currently `optimism_outputAtBlock` fails on op-reth because the proof window size defaults to 0. This sets it to 302400, which is roughly 1 week on a 2 second block time.
> chore: set proof window

- README.md
- network_params.yaml
- src/batcher/op-batcher/op_batcher_launcher.star
- src/cl/hildr/hildr_launcher.star
- src/cl/op-node/op_node_launcher.star
- src/contracts/contract_deployer.star
- src/el/op-besu/op_besu_launcher.star
- src/el/op-erigon/op_erigon_launcher.star
- src/el/op-geth/op_geth_launcher.star
- src/el/op-nethermind/op_nethermind_launcher.star
- src/el/op-reth/op_reth_launcher.star
- src/l2.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
- src/participant_network.star
This PR adds 2 configuration options and fixes handling of existing ones:
- `fund_dev_accounts` option is added to `network_params`, allowing to configure whether dev accounts should be funded on L2. In one of recent updates they stopped being funded by default, this PR changes it, let me know if this is undesired
- adds `batcher_image` option allowing to configure custom op-batcher image
- fixes handling of `el_extra_params`, right now this argument is not respected
- fixes handling of `seconds_per_slot`, right now this argument is not respected
Also it seems that `count` key for participants is no more respected. Is this intentional?
> fix: handling of config options

- README.md
- network_params.yaml
- src/package_io/input_parser.star
The tagged versions won't work without a predeployed OPCM, which only exists on mainnet and Sepolia.
> fix: Update default network params

- src/el/op-besu/op_besu_launcher.star
- src/el/op-erigon/op_erigon_launcher.star
- src/el/op-geth/op_geth_launcher.star
- src/el/op-nethermind/op_nethermind_launcher.star
- src/el/op-reth/op_reth_launcher.star
- src/el_cl_launcher.star
Closes #86 
Configure sequencer forwarding to send transactions to the sequencer EL RPC endpoint instead of the CL RPC endpoint.
Nightly workflow: https://github.com/leovct/optimism-package/actions/runs/12199976016
```bash
kurtosis run --enclave op --args-file .github/tests/op-geth.yaml .
export ETH_RPC_URL=$(kurtosis port print op op-el-2-op-geth-hildr-op-kurtosis rpc)
curl \
--request POST \
--url $ETH_RPC_URL \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--data '{"id":0,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0x02f8718320d5e480018476bb8201825208940000000000000000000000000000000000000000880de0b6b3a764000080c001a09322fe55a0a429fc26fc3703fea0e44298e28ac884afa448f1f9dd0ea6ac080ca07650448283d4afd481d7b690bb5251c75a7aca3a6e41d06cab49b …
```
> fix: sequencer forwarding

- .github/tests/rollup-boost.yaml
- README.md
- network_params.yaml
- src/el_cl_launcher.star
- src/l2.star
- src/mev/rollup-boost/rollup_boost_launcher.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
- src/participant_network.star
Option to add `rollup-boost` as an additional service. The rollup-boost image can be specified in mev_params.
> feat: integrate Rollup boost

- main.star
- src/l2.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
- src/participant_network.star
- src/proposer/op-proposer/op_proposer_launcher.star
Adds op-proposer support back in preparation for adding op-challenger support. We need proposer to make proposals to test challenger functionality.
The launcher supports a few config params:
```
{
"image": "",
"extra_params": [],
"game_type": 1,
"proposal_interval": "10m",
}
```
**Changes**
* Adds an l2_num param to l2, network participant launchers so we can index into the deployment state to get per-chain addresses
* Makes proposer parameters consistent with batcher
* Updates proposer to use dispute game factory
> feat: adds op-proposer support

- src/contracts/contract_deployer.star
Now that we have a top-level interop.enabled configuration flag, we
need to make sure op-deployer is configured accordingly.
> fix: set useInterop flag properly

- src/cl/op-node/op_node_launcher.star
op-node pointing to supervisor is now a configuration error, as per https://github.com/ethereum-optimism/optimism/pull/13406
> fix: stop pointing op-node to op-supervisor

- src/interop/op-supervisor/op_supervisor_launcher.star
This change is a workaround, considering that the http fallback should
work, but it's probably a better default anyway.
Main issue is tracked at:
https://github.com/ethereum-optimism/optimism/issues/13624
> fix: repair supervisor->node cnx

- src/contracts/contract_deployer.star
- src/util.star
given that run_sh uses /bin/sh, which doesn't support pipefail option,
the previous state allowed failures to not stop kurtosis execution
(the whole step itself didn't fail).
Beyond the inconvenience of having to scroll up to see the real
failure, it also potentially allowed kurtosis to *cache* the faulty
step, which would be very confusing at the next run.
> fix: remove some UUOC

- kurtosis.yml
This change makes consuming ethereum-package more predictable.
And more importantly, more reproducible.
Downside: obviously we'll need to bump that version every now and then.
> feat(reproduicibility): pin ethereum-package dependency

- src/cl/op-node/op_node_launcher.star
* Network should work without it and can be overridden if needed
> fix: removes op-node default param l1.trustrpc

- src/cl/op-node/op_node_launcher.star
- src/el/op-besu/op_besu_launcher.star
- src/el/op-erigon/op_erigon_launcher.star
- src/el/op-geth/op_geth_launcher.star
- src/el/op-nethermind/op_nethermind_launcher.star
- src/el/op-reth/op_reth_launcher.star
- src/package_io/constants.star
- src/util.star
The problem with selecting the last 63 characters of the image name
for a k8s label is that there's no guarantee that the result will
respect the other contraints.
In particular,
us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.4-rc.4
yields .pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.4-rc.4
which is invalid because it starts with a dot.
So the net outcome is that valid images fail to deploy because of an
invalid attached label.
This change select the longest prefix available while breaking only at /
So for the image above, the label would be
oplabs-tools-artifacts/images/op-geth:v1.101411.4-rc.4
> fix: don't truncate names too arbitrarily

- src/cl/hildr/hildr_launcher.star
- src/cl/op-node/op_node_launcher.star
* we removed the `l1.trustrpc` but now in some cases op-node times out waiting for enough confs to read the systemconfig (in particular when using pectra l1 geth test image?)
* fixes an unrelated bug in hildr causing nightlys to fail (note: they are will still fail for another upstream lighthouse package issue)
> fix: sets op-node sequencer/verifier confs to 2/1

- README.md
- network_params.yaml
- src/package_io/input_parser.star
- Bumping the default version of `op-deployer` due to the fact that the `isthmus_time_offset` was not being respected (and therefore `isthmusTime` did not end up in the genesis file)
> fix: Bump the default version of OP contract deployer

- src/participant_network.star
https://github.com/ethpandaops/optimism-package/pull/134 accidentally
broke the convention that an explicit "" for images meant using the
default ones.
This restores that behavior for now.
> fix: restore semantics of empty strings in input

- README.md
- main.star
- network_params.yaml
- src/alt-da/da-server/da_server_launcher.star
- src/batcher/op-batcher/op_batcher_launcher.star
- src/cl/hildr/hildr_launcher.star
- src/cl/op-node/op_node_launcher.star
- src/contracts/contract_deployer.star
- src/el_cl_launcher.star
- src/l2.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
- src/participant_network.star
Closes #67 
Example network_params.yaml with altda support:
```
optimism_package:
altda_deploy_config:
use_altda: true
da_commitment_type: KeccakCommitment
da_challenge_window: 100
da_resolve_window: 100
da_bond_size: 0
da_resolver_refund_percentage: 0
chains:
- participants:
- el_type: op-geth
cl_type: op-node
count: 1
network_params:
network: "kurtosis"
network_id: "2151908"
seconds_per_slot: 2
name: "op-kurtosis"
fjord_time_offset: 0
granite_time_offset: 0
fund_dev_accounts: true
da_server_params:
image: us-docker.pkg.dev/oplabs-tools-artifacts/images/da-server:latest
cmd:
- "da-server"
- "--file.path=/home"
- "--addr=0.0.0.0"
- "--port=3100"
- "--log.level=debug"
additional_services:
- da_server
op_contract_deployer_params:
image: …
```
> feat: alt-da support

- .github/workflows/per-pr.yml
- README.md
- mise.toml
*Description*
- `kurtestosis` has been renamed & migrated to [`kurtosis-test`](https://github.com/ethereum-optimism/kurtosis-test)
> chore: Use the renamed version of kurtestosis

- test/el_cl_launcher_test.star
- test/package_io/input_parser_test.star
*Description*
Following through with expanding the test coverage and feeding back the findings to the `kurtosis-test` package. 
The tests for `el_cl_launcher.star` required the addition of new `mock` functionality to `kurtestosis` ([see here](https://github.com/ethereum-optimism/kurtestosis/pull/8)) that allows us both to spy on arguments passed to module functions & mock their return values. This is useful if a non-pure function return value is returned from the tested code (like in this case with the sequence private key).
The tests should guide any future refactorings as they point out areas lacking separation of concerns or argument drilling.
> chore(test): Add stubs of unit tests for el_cl_launcher & input_parser

- src/cl/hildr/hildr_launcher.star
- src/cl/op-node/op_node_launcher.star
- test/el_cl_launcher_test.star
I would guess there's probably more missing but I needed these so figured I'd upstream the changes.
> chore: add missing log-level flags to node launchers

- README.md
- src/observability/grafana/grafana_launcher.star
- src/package_io/input_parser.star
Was getting this error
so uploaded the resources to `/dashboard-0` instead of the relative `dashboard-0` which docker wasn't accepting to mount.
Also made the dashboard provisioned by default. Can revert this change if you guys don't want it but I feel like everybody would be happy to have this by default.
> fix(grafana): use absolute file path

- src/cl/op-node/op_node_builder_launcher.star
- src/el/op-geth/op_geth_builder_launcher.star
- src/el/op-reth/op_reth_builder_launcher.star
- src/el_cl_launcher.star
- src/package_io/input_parser.star
Rollup-boost encountered issues due to configuration drift. 
While the primary drift problem was resolved in [PR #147](https://github.com/ethpandaops/optimism-package/pull/147), follow-up testing uncovered additional inconsistencies that require further adjustments. 
This issue proposes targeted fixes based on local test results and addresses the rest of inconsistencies.
Also couple of uncovered bugs were addressed (mainly with external builder)
Removed [this](https://github.com/ethpandaops/optimism-package/blob/0d490fd395ee579ea905bb4633e453e27e075bb8/src/el_cl_launcher.star#L354) as it was causing a bug + was confusing
Changed behavior of builder consensus node. Now if external builder is used it should setup consensus node outside of enclave too.
> fix: additional fixes for rollup-boost drift

- src/el_cl_launcher.star
This PR adds following flags to builder EL deployments:
```
--rollup.sequencerhttp=<EL l2 url>
--bootnodes=enode://<EL l2 enode>
``` 
--bootnodes flag is added via moving insert to all_el_contexts before calling el_builder_launch_method
--rollup.sequencerhttp is added by passing sequencer_enabled=False
> feat: EL builder sequencer and bootstrap issues

- README.md
Added alternative way to spam transaction in the devnet with contender
https://github.com/flashbots/rbuilder/issues/418
> feat: Add docs section about using contender as l2 transaction source

- src/batcher/op-batcher/op_batcher_launcher.star
- src/challenger/op-challenger/op_challenger_launcher.star
- src/el_cl_launcher.star
- src/mev/rollup-boost/rollup_boost_launcher.star
- src/observability/observability.star
- src/package_io/constants.star
- src/package_io/input_parser.star
- src/participant_network.star
- src/proposer/op-proposer/op_proposer_launcher.star
This PR improves the way the `service`, `namespace`. and `stack_optimism_io_network` labels are applied to services, in order to enable per-replica filtering in Grafana dashboards.
These changes have been successfully tested with a 2-replica params file:
Resolves #182.
> fix(observability): label improvements

- README.md
- src/interop/op-supervisor/op_supervisor_launcher.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
Missed to add network param for supervisor at https://github.com/ethpandaops/optimism-package/pull/185.
Dodges below error when interop is enabled.
```
: interpretation error: Evaluation error: function register_op_service_metrics_job missing 1 argument (network_name)
at [github.com/ethpandaops/optimism-package/main.star:130:38]: run
at [github.com/ethpandaops/optimism-package/src/interop/op-supervisor/op_supervisor_launcher.star:79:50]: launch
at [github.com/ethpandaops/optimism-package/src/observability/observability.star:87:5]: register_op_service_metrics_job
```
> fix(observability): network label for supervisor

- README.md
- src/interop/op-supervisor/op_supervisor_launcher.star
- src/observability/observability.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
This PR follows up on the fix made in https://github.com/ethpandaops/optimism-package/pull/187 to make the network label optional, as `op-supervisor`is an interop component and hence not specific to any one network.
> fix(observability): remove supervisor network label

- src/challenger/op-challenger/op_challenger_launcher.star
TraceTypeSupper{Cannon|Permissioned} needs --cannon-depset-config to be set, which was added at https://github.com/ethereum-optimism/optimism/pull/14666 
Introduce a temporary fix to add a dummy flag.
We need a eventual full fix; will be tracked at https://github.com/ethpandaops/optimism-package/issues/189
validated that monorepo interop kt devnet spins up, which includes `super-cannon` trace type at challenger config.
> fix: Add depset-config dummy flag for challenger

- src/contracts/contract_deployer.star
This change does 2 things in one:
- actually point to a reasonable cache value in the context of a container
- sidestep an issue with op-deployer where the default is invalid (empty)
> fix: explicitly set op-deployer cache to a reasonable value

- main.star
This PR defaults the `optimism_package` configuration block to an empty dictionary if none is provided by the user in order to fix an issue introduced in https://github.com/ethpandaops/optimism-package/pull/166.
> fix: default optimism_args to empty

- justfile
- mise.toml
This change makes use of a tool developed separately:
https://github.com/ethereum-optimism/kurtosis-lint to identify common
pitfalls while developing Kurtosis starlark code.
To give a quick idea, I broke a bunch of things on purpose, and the tool complained:
Running analysis...
.../optimism-package/main.star:2: Imported module './src/contracts/contract_deploy.star' does not exist at resolved path '.../optimism-package/src/contracts/contract_deploy.star'
.../optimism-package/main.star:40: Call to non-existent function 'input_parse' in module 'input_parser'
.../optimism-package/main.star:50: Too many positional arguments in call to 'observability.star:make_helper'
.../optimism-package/main.star:90: Module 'contract_deployer' has not been analyzed for call to …
> feat: add new lint tool

- src/el_cl_launcher.star
This PR fixes a logic bug when provisioning network participants where all participants were mistakenly configured as sequencers.
Follow-up to [this PR](https://github.com/ethpandaops/optimism-package/pull/178).
[Context](https://discord.com/channels/1244729134312198194/1351230618733776987)
> fix: single sequencer

- src/util.star
Calls to write_file are currently the only ones that create artifacts
with generated names, which is needlessly getting in the way of
looking at the outcomes.
We have 2 call sites for this function:
- dependency_set.json
- intent.json
Arguably the latter is not super useful to expose, as it's an
intermediate representation of what eventually lands in
op-deployer-configs, but it doesn't hurt either.
> fix(util): name artifacts created by write_to_file

- src/proxyd/proxyd_launcher.star
We have as many instances of proxyd as we have L2 networks.
Therefore we need to create a unique artifact name for each of their
configurations.
Also fix the svc name, which used network instead of network_id
> fix(proxyd): uniquify proxyd-config artifact

- README.md
- justfile
- main.star
- src/alt-da/da-server/da_server_launcher.star
- src/batcher/op-batcher/op_batcher_launcher.star
- src/blockscout/blockscout_launcher.star
- src/challenger/op-challenger/op_challenger_launcher.star
- src/cl/op-node/op_node_builder_launcher.star
- src/cl/op-node/op_node_launcher.star
- src/contracts/contract_deployer.star
- src/el/op-besu/op_besu_launcher.star
- src/el_cl_launcher.star
- src/l2.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
- src/participant_network.star
- src/proposer/op-proposer/op_proposer_launcher.star
- src/signer/op_signer_launcher.star
- src/signer/templates/config.yaml.tmpl
- src/util.star
- test/el_cl_launcher_test.star
- test/op_challenger_launcher_test.star
- test/test_utils.star
- test/util_test.star
This PR provisions an `op-signer` instance per network in order to support signing batcher/proposer/challenger transactions. It leverages the local KMS support added in [this PR](https://github.com/ethereum-optimism/infra/pull/252) in order to reuse the existing client private keys, which it converts from raw hex strings to PEM format.
It uses the `op-signer/gen-local-creds.sh` script (updated in [this PR](https://github.com/ethereum-optimism/infra/pull/265)) to generate mTLS credentials to authenticate connections between `op-signer` and its clients.
Resolves https://github.com/ethereum-optimism/platforms-team/issues/581.
> feat(op-signer): add op-signer support

- network_params.yaml
- src/package_io/input_parser.star
Setting teku away from latest, as their latest branch requires support for fulu. Fulu is not yet supported in the older version of ethereum package that optimism-package is using. So the workaround is to use an older version of teku, and then eventually once there will be a new release for ethereum package, then we can pin it to that, and use the client releases.
> fix: teku set older version

- src/el_cl_launcher.star
- test/el_cl_launcher_test.star
- test/main_test.star
- EL/CL names were not unique within an enclave, only within an L2 network. This meant that individual L2 networks were missing clients
> fix: Fix missing EL/CL with multiple chains

- kurtosis.yml
- network_params.yaml
- src/package_io/input_parser.star
The pinning was initially needed for optimism monorepo sanity, but we
have a way to pin there instead.
Also revert the teku version pinning that was needed because of it.
Pinning at this level causes unncessary friction, as it sets the
lowest possible synchronization point for downstream consumers.
> chore: unpin ethereum-package

- README.md
- main.star
- mise.toml
- src/interop/constants.star
- src/interop/op-supervisor/op_supervisor_launcher.star
- src/l2.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
- src/participant_network.star
- src/util.star
- test/interop/op-supervisor/op_supervisor_launcher_test.star
- test/package_io/input_parser_test.star
- test/util_test.star
Adds a concept of interop sets so that `op-supervisor` can be set up with more nuance.
Interop sets get their configuration section under `interop.sets`. A single interop set binds several L2 chains (referenced by their network IDs) into an interoperable system.
- The `participants` field refers to network IDs of the L2 chains. Special value `*` can be used to quickly assign all L2s into a single interop set. To simulate misconfiguration, a single L2 can be assigned to multiple interop sets
- `supervisor_params` can override default supervisor parameters under `interop.supervisor_params`
- Interop is enabled if there is at least one interop set. It can be disabled explicitly either as a whole or per-interop-set using `interop.enabled` and `interop.sets[].enabled` boolean …
> feat: Per-interop-set supervisor

- main.star
- network_params.yaml
- src/challenger/op-challenger/op_challenger_launcher.star
- src/interop/constants.star
- src/interop/op-supervisor/op_supervisor_launcher.star
- test/interop/op-supervisor/op_supervisor_launcher_test.star
- test/op_challenger_launcher_test.star
This PR fixes the challenger <> supervisor communication broken by #220. The system has become more complex and constant `SUPERVISOR_ENDPOINT` is no longer sufficient.
This constant is still being used in several places - besides `op-geth` though its usages can be removed to (almost) break the circular dependency between `el` <> `supervisor`
Relates to https://github.com/ethereum-optimism/optimism/issues/15151
> fix: Fix challenger <> supervisor interaction

- main.star
- src/faucet/op-faucet/config.tmpl
- src/faucet/op-faucet/op_faucet_launcher.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
- src/participant_network.star
- test/op_faucet_launcher_test.star
This adds preliminary support for op-faucet.
see https://github.com/ethereum-optimism/optimism/tree/develop/op-faucet
An official image doesn't exist for it yet, so there will need to be a
followup once this is addressed.
This is a test-only construct.
When enabled, we have an unrestricted faucet tied to the (funded)
faucet wallets.
Each chain in the devnet (l1, and all l2s) are mapped to this faucet.
> feat: add op-faucet component

- .github/workflows/conventional-pr-title-checker.yml
- .github/workflows/per-pr.yml
- .github/workflows/release-please.yml
- .github/workflows/reusable-run-k8s.yml
- .github/workflows/scheduled-k8s.yml
The `run_k8s_test` workflow has been used for both PRs and for scheduled pipelines. The concurrency setting has been tailored for the scheduled usecase, which meant that for some PRs this workflow would have been skipped and they would not be mergeable.
> fix: Fix k8s pipeline configuration

- src/util/expansion.star
- src/util/filter.star
- test/util/expansion_test.star
- test/util/filter_test.star
The multiple supervisor support will require a rework of a significant part of the challenger, L2 and supervisor code. To make the new code DRYer, we are creating utilities for working with dicts and lists:
- `filter.star`
- `remove_none` for removing `None` values from `dict`s. YAML supports `None` o it's important we strip these out before merging any dictionaries with default values
- `remove_keys` for removing a list of keys from `dict`s. This will be a part of the replacement for the centralized `sanity_check` functions - we will use it to fail the process if we find any unknown properties on a configuration object.
- `expansion.star`
- `expand_asterisc` for working with special `"*"` values that mean _all_. This will be used in places where a configuration object …
> chore: Support multiple supervisors: utilities [1/N]

- main.star
- src/interop/op-supervisor/launcher.star
- Rename `op_supervisor_launcher/op_supervisor_launcher.star` to just `op_supervisor_launcher/launcher.star` - no need to make things double explicit
- Make the `launch` function return a `struct` with a standard `service` property. This convention will enable us to have consistent code when chaining launchers.
Related to https://github.com/ethereum-optimism/optimism/issues/15611
> chore: Support multiple supervisors: Convention for launcher filenames - op-supervisor [2/N]

- src/l2.star
- src/participant_network.star
Removes unused `challenger_params` parameter from `l2` and `participant_network`. Removes an unused import as well
Related to https://github.com/ethereum-optimism/optimism/issues/15611
> chore: Support multiple supervisors: Remove unused params [3/N]

- .github/workflows/nightly.yml
- .github/workflows/per-pr.yml
- justfile
- mise.toml
Small CI pipeline cleanups to speed things up, add linting etc.
- Add `just` as a dependency to `mise.toml` and use `mise` across the board instead of manual installation
- Remove outdated conditionals in CI pipeline
- Add `lint-style` and `lint-code` `just` targets and make them both run when running `just lint`
- Add `fix-style` just target. It was less words to rewrite the target than to parameterize the `lint-style` one
- Add `test` `just` targets
> chore: Clean up pipelines

- network_params.yaml
- src/challenger/op-challenger/launcher.star
- src/contracts/contract_deployer.star
- src/observability/observability.star
- src/package_io/input_parser.star
This updates the cannon vmType used, and the op-deployer version that supports it
Also fix some issues:
- rpc endpoints don't like multiple participants, we'll need some proxy there eventually
- observability job names are not unique enough
> fix(cannon): update cannon vm type after type 2 was removed

- src/contracts/contract_deployer.star
- src/package_io/input_parser.star
- src/package_io/sanity_check.star
This adds the ability to override the vmType as part of op-deployer operations.
main use-case will probably be to use CANNON-NEXT in some experiments.
We also rename global_deployer_overrides to simply overrides as it
doesn't properly match op-deployer's intent's globalDeployOverrides
concept anymore.
Also rework the overrides mechanism so we can actually specify a subset of the overrides.
> fix(op-deployer): allow overriding cannon vm type

- main.star
- src/el_cl_launcher.star
- src/l2.star
- src/package_io/input_parser.star
- src/package_io/registry.star
- src/package_io/sanity_check.star
- src/participant_network.star
- src/proxyd/proxyd_launcher.star
- test/op_faucet_launcher_test.star
- test/package_io/registry_test.star
- test/tx_fuzzer_launcher_test.star
This change adds a concept of registry for the various container images we handle.
It has several purposes:
- to centralize the definition of the container images we use
- to make it overridable by a downstream consumer
In particular, this improves the reprodicibility capabilities of the
package, as said downstream consumers can pin specific versions of the
packages being used, in a way that's orthogonal to the arguments
definition that's passed to the package.
See https://github.com/ethereum-optimism/optimism/pull/15697 for an example.
The *defaults* are pinned, without affecting the ability to override
images on a per-component instance basis.
> feat: add overridable registry

- mise.toml
- src/interop/op-supervisor/launcher.star
- src/util.star
- src/util/file.star
- test/util/file_test.star
A precursor for multiple supervisor support and performance improvement for creating files from static (interpretation-time) strings.
> chore: Support multiple supervisors: Create files from interpretation-time strings [4/N]

- src/util/net.star
- test/util/net_test.star
Adds a collection of network utilities to support the multiple supervisor logic to come:
- `port` function that creates a struct similar to `PortSpec` - with the advantage of it being compatible with deep equality from `assert` module (`assert` does not handle comparisons of custom objects). Config parsers create these objects before the services are launched which comes handy when there is a network-based circular dependency between services
- `port_to_port_spec` and `ports_to_port_specs` to convert `port` structs to `PortSpec` objects for when a service is created from config
- `service_url` to create a URL from a service name and a `port`/`PortSpec` object.
> chore: Support multiple supervisors: Network utilities [6/N]

- src/package_io/input_parser.star
- src/package_io/sanity_check.star
- src/superchain/input_parser.star
- test/superchain/input_parser_test.star
Adds new input parsers for superchain configuration, to be plugged in in the next steps. Builds on top of #255 
> chore: Support multiple supervisors: Superchains input parsers [7/N]

- src/package_io/input_parser.star
- src/package_io/sanity_check.star
- src/supervisor/input_parser.star
- src/util/filter.star
- test/supervisor/input_parser_test.star
- test/util/filter_test.star
- Adds input parsers for new top-level key `supervisors`. The parsers are plugged in but not acted upon.
- Adds a `first` filtering utility that takes the first elements out of the list in a safe way
Builds on top of #254 
> chore: Support multiple supervisors: Supervisor parsers [8/N]

- src/superchain/input_parser.star
- src/util/net.star
- test/superchain/input_parser_test.star
- Adds an interop RPC port to the superchain params. This port is exposed on CL clients so eventually it will move there
> chore: Support multiple supervisors: Add interop RPC port to superchain params [11/N]

- src/superchain/input_parser.star
- src/superchain/launcher.star
- src/supervisor/input_parser.star
- test/superchain/input_parser_test.star
- test/superchain/launcher_test.star
- test/supervisor/input_parser_test.star
- Moves the `dependency_set` from `supervisors` to `superchains`. For now we'll not allow custom dependency set, we'll add that on demand
> chore: Support multiple supervisors: Move dependency sets under superchains [12/N]

- src/superchain/input_parser.star
- src/superchain/launcher.star
- src/supervisor/op-supervisor/launcher.star
- test/superchain/input_parser_test.star
- test/supervisor/op-supervisor/launcher_test.star
- Adds new `op-supervisor` launcher without plugging it in yet
- Adds `path` property to `dependency_set` in `superchain/input_parser` so that we don't need to pass the result of `superchain/launcher` to `op-supervisor/launcher`
> chore: Support multiple supervisors: Add op-supervisor launcher [13/N]

- src/superchain/launcher.star
- test/superchain/launcher_test.star
- Launchers should accept single objects, not lists or dicts
> chore: Support multiple supervisors: Fix launcher pattern for superchain [15/N]

- network_params.yaml
- src/challenger/input_parser.star
- src/superchain/input_parser.star
- src/supervisor/input_parser.star
- src/util/id.star
- test/challenger/input_parser_test.star
- test/el_cl_launcher_test.star
- test/superchain/input_parser_test.star
- test/superchain/launcher_test.star
- test/supervisor/input_parser_test.star
- test/supervisor/op-supervisor/launcher_test.star
This ensures that both supervisor and challenger provide enough
information in the service names to figure out which chains they
relate to.
For challenger, a list of participants.
For supervisor, just a reference to the corresponding dependency set.
> fix(superchain): encode related chains in service names

- .github/tests/external-l1/ethereum.yaml
- .github/tests/external-l1/optimism.yaml
- network_params.yaml
- src/package_io/input_parser.star
Teku currently have some issues with the newly introduced BPO file structure so I suggest to use lighthouse as the default CL for now.
> fix: default L1 CL to lighthouse

- src/el/input_parser.star
- src/l2/participant/cl/input_parser.star
- src/l2/participant/el/input_parser.star
- src/l2/participant/input_parser.star
- src/util/net.star
- test/l2/participant/input_parser_test.star
- Adds new input parsers for EL, CL and adds them under a participant parser. The prefixed version (`el_something_something`, `c_something_something`) has been replaced by nested objects (prefixes typically point to a lack of nesting), which simplifies the parsing logic
- Despite the EL & CL parsing being quite similar, I kept them in separate parsers to allow them to diverge and not to obscure simple parsing with complex abstractions. We'll see if this stands the test of time
- `labels` have been added to the parsed params to see whether we could use those
The names of the services have changed and should be more readable (which will incur a cost on the devnet SDK parsing side). I am not set on this particular format, but improvement is necessary, feel free to suggest …
> chore: Support multiple sequencers: Stub of L2 network participant input parsers [1/N]

- src/mev/rollup-boost/rollup_boost_launcher.star
A recent audit outlined that the default socket address at which rollup-boost establishes the RPC server is `0.0.0.0` which makes it vulnerable to misconfiguration. I'm working on a PR to change the default socket address to `127.0.0.1` but it currently breaks the kurtosis integration tests.
This PR fixes it by explicitly setting the RPC host to `0.0.0.0`
> refactor: Explicitlly specify rollup-boost socket addr in cli args

- src/el/input_parser.star
- src/util/filter.star
- src/util/id.star
- test/util/filter_test.star
- test/util/id_test.star
- Adds `get_duplicates` helper utility to isolate e.g. network ID duplicate detection from the massive launcher files
- Adds `autoincrement` ID generator to isolate network ID generation from the very same massive launcher
> chore: Support multiple sequencers: Additional filter & ID utilities [2/N]

- mise.toml
- src/el/input_parser.star
- src/l2/input_parser.star
- src/l2/participant/input_parser.star
- test/l2/input_parser_test.star
- test/l2/participant/input_parser_test.star
- Adds an L2 input parser that checks the `network_params` and uses the existing parsers to add `EL` & `CL` params
- Updates `kurtosis-test` to a version that silenced logging a bit when testing using `--test-pattern` - the important logs were getting drowned in the warnings about tests not matching a pattern
> chore: Support multiple sequencers: Add stub of L2 input parser [3/N]

- main.star
- src/supervisor/op-supervisor/launcher.star
- test/supervisor/op-supervisor/launcher_test.star
https://github.com/ethereum-optimism/optimism/pull/16038 introduces a new required command line flag/env var `OP_SUPERVISOR_ROLLUP_CONFIG_PATHS`.
> fix(supervisor): Add new rollup config set to launcher

- main.star
- src/cl/op-node/op_node_launcher.star
- test/el_cl_launcher_test.star
Consequence of https://github.com/ethereum-optimism/optimism/pull/16094
> fix(op-node): Add depdencency set env var to op-node

- src/package_io/registry.star
- test/l2/input_parser_test.star
- test/proxyd/input_parser_test.star
This PR adds upgrades the proxyd version to v4.14.5.
**Tests**
**Additional context**
**Metadata**
> fix(proxyd): upgrade to v4.14.5

- src/l2/participant/input_parser.star
- src/mev/input_parser.star
- src/package_io/input_parser.star
- test/l2/participant/input_parser_test.star
- test/mev/input_parser_test.star
MEV (rollup boost) is a per-sequencer service and needs to move under the participant configuration if we are to support multiple sequencers.
This PR adjusts the new input parser and plumbs it back into the legacy `package_io/input_parser.star` for the time being.
> chore: Support multiple sequencers: Move MEV under participant [13/N]

- src/l2/participant/cl/input_parser.star
- src/util/net.star
- test/l2/participant/input_parser_test.star
- Add missing CL ports to the input parser
- Rename misnamed "beacon" port to "rpc"
This is a follow up for [a discord discussion here](https://discord.com/channels/1244729134312198194/1377805358487044106)
> chore: Support multiple sequencers: CL ports [14/N]

- src/package_io/registry.star
In parallel with the multiple sequencers support, this series of PRs will introduce functionality required to run `op-conductor`.
As soon as the multiple sequencers series is finished, we can plumb this in.
> chore: Conductor support: Add op-conductor image to the registry [1/N]

- src/l2/input_parser.star
- src/package_io/input_parser.star
- src/participant_network.star
- src/proxyd/input_parser.star
- src/proxyd/launcher.star
- test/l2/input_parser_test.star
- test/proxyd/input_parser_test.star
Since we know the EL URLs in advance, we can add them to the proxyd parsed params instead of synthesizing them in the launcher. This makes the launcher thinner and will make the transition from the old to the new input parser a bit slimmer.
It requires a bit of forward plumbing in the current input parser - to map the legacy parsed participants to the new format (only the bits required by the `proxyd` launcher)
> chore: Support multiple sequencers: Add EL URLs to parsed proxyd params [16/N]

- src/l2/participant/el/input_parser.star
- src/util/net.star
- test/l2/participant/input_parser_test.star
Adds all the EL ports to the input parser and cleans up some test files containing string literals instead of `net` constants
> chore: Support multiple sequencers: Add missing ports to EL input parser [20/N]

- src/el/op-besu/launcher.star
- src/el/op-erigon/launcher.star
- src/el/op-geth/launcher.star
- src/el/op-nethermind/launcher.star
- src/el/op-reth/launcher.star
- src/l2/launcher.star
- src/l2/participant/el/launcher.star
- src/l2/selectors.star
- src/package_io/constants.star
- test/l2/participant/el/launcher_test.star
- test/l2/selectors_test.star
- Adds new launchers (alongside the old ones, until we migrate the whole thing) for EL nodes. The contents of these launchers have been left as they were, with the changes being only the dynamic ports coming from the parsed params
- Adds a helper selector utility to get sequencer params from participant params. We'll need this since the EL clients receive a CLI flag pointing to their sequencer's URL
> chore: Support multiple sequencers: Launchers for EL clients [21/N]

- src/l2/input_parser.star
- test/l2/input_parser_test.star
If there are no networks defined in the args file, we'll create a default network called `opkurtosis`
> chore: Support multiple sequencers: Provide default network if nothing was set [22/N]

- src/conductor/op-conductor-ops/config.toml.tmpl
- src/conductor/op-conductor-ops/launcher.star
- src/package_io/registry.star
`op-conductor-ops` is required when launching conductor instances. This PR introduces a disconnected launcher that runs a `bootstrap-cluster` command followed by a `status` command just for visibility purposes
> fix: Support multiple sequencers: Add op-conductor-ops launcher [27/N]

- network_params.yaml
- src/conductor/input_parser.star
- src/conductor/op-conductor/launcher.star
- src/package_io/registry.star
- src/package_io/sanity_check.star
- src/participant_network__hack.star
- test/conductor/input_parser_test.star
- test/l2/participant/input_parser_test.star
`op-conductor` needs to know about the supervisors, hence this.
We also need to pass the `rollup-boost` context to the conductor but it's buried so deep in the `el_cl_launcher` that we'd need to go through with the full refactor to support it (sad face).
Fixes https://github.com/ethereum-optimism/optimism/issues/16366
> fix: Support multiple sequencers: Pass supervisors params to conductor [29/N]

- .github/tests/blockscout.yaml
- README.md
- network_params.yaml
- src/blockscout/input_parser.star
- src/blockscout/launcher.star
- src/l2.star
- src/l2/input_parser.star
- src/l2__hack.star
- src/package_io/input_parser.star
- src/package_io/registry.star
- src/package_io/sanity_check.star
- test/blockscout/input_parser_test.star
- test/l2/input_parser_test.star
Moves `blockscout` config to the new format, adds an input parser and updates the launcher
> chore: Support multiple sequencers: Input parser & launcher for blockscout [34/N]

- src/challenger/input_parser.star
- src/challenger/op-challenger/launcher.star
- src/conductor/input_parser.star
- src/faucet/op-faucet/op_faucet_launcher.star
- src/l2/participant/cl/input_parser.star
- src/l2/participant/el/input_parser.star
- src/l2/participant/input_parser.star
- src/mev/input_parser.star
- src/package_io/input_parser.star
- src/proxyd/launcher.star
- src/supervisor/input_parser.star
- src/supervisor/kona-supervisor/launcher.star
- src/supervisor/op-supervisor/launcher.star
- test/challenger/input_parser_test.star
- test/conductor/input_parser_test.star
- test/l2/participant/cl/launcher_test.star
- test/l2/participant/el/launcher_test.star
- test/l2/participant/input_parser_test.star
- test/mev/input_parser_test.star
- test/supervisor/input_parser_test.star
This PR adds missing and new labels to OP services:
- `op.network.participant.index` label to EL, CL, conductor and MEV to emulate the legacy
- Labels for challenger
- Labels for faucet
> chore: chore: Support multiple sequencers: Missing labels [38/N]

- src/l2/input_parser.star
- src/l2/participant/input_parser.star
- src/util/id.star
- test/l2/input_parser_test.star
- test/l2/participant/input_parser_test.star
- test/util/id_test.star
With the switch to label-based parsing, the ID assertions have changed
> chore: Support multiple sequencers: Update ID assertions [39/N]

- src/faucet/op-faucet/op_faucet_launcher.star
This change sets the faucet labels properly, so we can use them in
service recognition downstream.
> fix(op-faucet): set op.network.id label

- src/faucet/op-faucet/op_faucet_launcher.star
- test/op_faucet_launcher_test.star
Network IDs can be expressed as integers in the yaml descriptor.
Handle the faucet label in a more robust manner.
> fix(op-faucet): loosen expectation on network_id type

- src/el/op-besu/launcher.star
- src/el/op-erigon/launcher.star
- src/el/op-geth/launcher.star
- src/el/op-nethermind/launcher.star
- test/el/launcher_test.star
The log levels in most EL clients were either missing, misconfigured or both. This PR adds the correct CLI params and their values
Fixes https://github.com/ethereum-optimism/optimism/issues/17011
> fix: EL log levels

- src/package_io/registry.star
- test/signer/input_parser_test.star
Slimming down the launcher PR by slicing off soma small chunks:
- Updating the default `op-signer` image
- Adding an `openssl` image (used by the signer to generate certificates)
Related to https://github.com/ethereum-optimism/platforms-team/issues/581
> feat: op-signer: Add & update images [2/N]

- src/batcher/op-batcher/launcher.star
- src/l2/launcher__hack.star
- src/proposer/op-proposer/launcher.star
- test/batcher/op-batcher/launcher_test.star
- test/proposer/op-proposer/launcher_test.star
Connects the now running signer service to the proposer. Some small unused clutter from the proposer launcher has been removed as well.
Related to https://github.com/ethereum-optimism/platforms-team/issues/581
> feat: op-signer: Connect the signer to the proposer [8/N]

- .github/scripts/kurtosis-check-block-progression.sh
- .github/scripts/kurtosis-dump-logs.sh
- .github/workflows/actions/run-kurtosis-docker/action.yaml
- .github/workflows/actions/setup-environment/action.yaml
- .github/workflows/nightly.yml
- .github/workflows/per-pr.yml
Based on [my PR to `op-reth`](https://github.com/ethereum-optimism/op-reth/pull/57)
- Adds a smoke test that checks the block progression of the network under test
- Adds a helper script that dumps logs formatted for github UI (using the collapsible groups)
- Always stores log artifacts - there seem to be cases when the pipeline is green yet something somewhere did not go well (currently investigating two issues where this happened)
- Encapsulate setup action into its own composite action not to duplicate code all over the place. Unfortunately, since the workflow needs to have the repo code in order to run this action, we cannot smack the checkout there as well
> chore: Add a script that checks block progression for test enclaves

- src/conductor/input_parser.star
- test/conductor/input_parser_test.star
- test/da/input_parser_test.star
- test/flashblocks/flashblocks-rpc/input_parser_test.star
- test/flashblocks/flashblocks-web-proxy/input_parser_test.star
- test/l2/participant/input_parser_test.star
- test/mev/input_parser_test.star
- test/proposer/input_parser_test.star
- test/proposer/op-proposer/launcher_test.star
- test/proxyd/input_parser_test.star
- test/signer/input_parser_test.star
- test/tx_fuzzer/input_parser_test.star
Supplying a dynamic healthcheck interval that defaults to `2 * blocktime + 1`
Related to https://github.com/ethereum-optimism/optimism/issues/16514
> chore: Dynamic healthcheck  interval for conductor
