ethpandaops/optimism-package

README.md, main.star, network_params.yaml, src/contracts/contract_deployer.star, src/l2.star, src/package_io/input_parser.star, src/package_io/sanity_check.star
=> feat: add op_contract_deployer_params/image

src/package_io/input_parser.star, static_files/chainspec_template/gen2spec.jq
- Update Nethermind image; 
- Improve genesis generation tool for Nethermind.
=> fix: Update neth image; improve genesis tool

static_files/scripts/gen2spec.jq
Recently we've added support for the upcoming Optimism hard-fork Holocene in Nethermind (https://github.com/NethermindEth/nethermind/pull/7761) and the OP team suggested us to use OP's kurtosis package to test it.
We found a couple of issues when trying to set up an enclave due to certain changes to other fork's timestamps which would trigger an error in Nethermind. To fix that, one of our developers (@flcl42) updated the `gen2spec.jq` script which fixes the above mentioned issue.
=> fix: Update Nethermind scripts for Holocene

README.md, main.star, src/contracts/contract_deployer.star
* fix lint error introduced in previous PR.
* Update readme with instructions to run linter and also add tx-fuzz running instructions
=> chore: Fix lint and update README

src/cl/op-node/op_node_builder_launcher.star, src/el/op-geth/op_geth_builder_launcher.star, src/el/op-reth/op_reth_builder_launcher.star, static_files/scripts/fund.sh
rollup boost nightly build is failing due to plan errors from merge / rebase issues
=> fix: rollup boost plan errors

.github/workflows/per-pr.yml, mise.toml
*Description*
`kurtosis` can be installed using `mise` which simplifies things on the CI & makes life easier for devs
=> chore: Install kurtosis using mise

test/el_cl_launcher_test.star
*Description*
- Extend the `el_cl_launcher_test.star` with a simple test for `op-besu`
- Extract some test input defaults on top of the file
=> chore(test): Add simple launcher test for op-besu

src/mev/rollup-boost/rollup_boost_launcher.star
This PR updates the rollup-boost flags with the latest changes.
=> feat: update rollup-boost params

.github/workflows/conventional-pr-title-checker.yml, .github/workflows/nightly.yml, .github/workflows/per-pr.yml, .github/workflows/run-k8s.yml
Adding the specific versions as a comment
=> chore(ci): Update github actions dependencies to show full versions in comment

.gitignore, justfile
- Also lint `test/` directory
- Ignore `.kurtosis-test`temp directory
=> chore: Fix lint & temp files

network_params.yaml, src/contracts/contract_deployer.star, src/package_io/input_parser.star
CANNON1 is very very old; we should use the newer CANNON7.
=> fix(contracts): use newer cannon

network_params.yaml, src/challenger/op-challenger/launcher.star, src/contracts/contract_deployer.star, src/l2.star, src/package_io/input_parser.star, src/participant_network.star
op-deployer changed some names in state.json and intent.toml
bump op-deployer release and adjust the code accordingly
=> fix: adjust for new op-deployer

mise.toml
No functional change, just using more recent versions of the underlying dev tools, and kurtosis.
=> chore: update toolchain

src/builder/op-geth/op_geth_launcher.star, src/builder/op-rbuilder/op_rbuilder_launcher.star, src/cl/kona-node/kona_node_launcher.star, src/cl/op-node/op_node_builder_launcher.star, src/cl/op-node/op_node_launcher.star
Yet another cleanup to reduce the number of changed lines in the bigger PR
=> chore: Support multiple supervisors: Get more ballast out of the way [14/N]

src/batcher/input_parser.star, src/batcher/op-batcher/launcher.star, src/el/input_parser.star, src/l2/input_parser.star, src/package_io/input_parser.star, src/participant_network.star, test/batcher/input_parser_test.star, test/l2/input_parser_test.star
=> chore: Support multiple sequencers: Input parser & launcher for op-batcher [5/N]

src/cl/hildr/launcher.star, src/cl/kona-node/launcher.star, src/l2/participant/cl/launcher.star, src/package_io/constants.star, test/l2/participant/cl/launcher_test.star
- Fixes several missing constants (surprised we haven't run into these)
- Adds a launcher for CL that wraps the individual CL launchers. The contents of these have not been examined thoroughly so any existing problems might still lurk there
=> chore: Support multiple sequencers: Launchers for CL clients [19/N]

src/conductor/input_parser.star, src/l2/participant/input_parser.star, src/util/net.star, test/conductor/input_parser_test.star, test/l2/participant/input_parser_test.star
Input parser for conductor, not plugged in to the L2 participant input parser yet
=> chore: Conductor support: Input parser [2/N]

src/package_io/registry.star
op-faucet is now published alongside other official images.
=> fix(registry): use published op-faucet image

README.md, src/package_io/registry.star, src/util.star, test/da/input_parser_test.star, test/l2/input_parser_test.star, test/l2/participant/input_parser_test.star, test/mev/input_parser_test.star, test/package_io/registry_test.star
The remaining mutable tags have been fixed at their equivalents as of the time of writing this PR. This change first needs to be communicated so don't merge yet please
=> chore: Pin remaining docker images

mise.toml
You wouldn't believe it but this PR updates kurtosis to 1.10.3
=> chore: Update kurtosis to 1.10.3
